@host = https://app-spring-progrados.herokuapp.com

GET {{host}}/employees HTTP/1.1
Accept: application/json

GET {{host}}/employee/3 HTTP/1.1
Accept: application/json

POST {{host}}/employee HTTP/1.1
Content-Type: application/json

{
    "firstName" : "Test8",
    "lastName" : "Test8"
}

DELETE {{host}}/employee/2 HTTP/1.1
Accept: application/json

PUT {{host}}/employee HTTP/1.1
Content-Type: application/json

{
    "id":"3",
    "firstName" : "Orestes",
    "lastName" : "La Cunza"
}
