GET http://localhost:8080/employees HTTP/1.1
Accept: application/json

POST http://localhost:8080/employee HTTP/1.1
Content-Type: application/json

{
    "firstName" : "Test4",
    "lastName" : "Test4"
}